name: jannikfalkner.de
meta_description: "Jannik's Website - jannikfalkner.de. All about my projects."

aboutPage: true

baseurl: /
domain_name: 'http://jannikfalkner.de'
google_analytics: 'UA-55896614-1'
disqus: false

# Details for the RSS feed generator
url:            'http://jannikfalkner.de'
author:         'Jannik Falkner'
authorTwitter:  'jannnik'

permalink:       /:categories/:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
